version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install package
      - cp target/registration*.war registration.war
      - zip registration.zip registration.war appspec.yml scripts/*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/registation.war
